# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Onbeperkt 4G Zakelijk
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Ontdek de beste zakelijke 4G-abonnementen met onbeperkte data bij Onbeperkt 4G Zakelijk. Vergelijk moeiteloos opties, lees betrouwbare reviews en vind het perfecte abonnement dat past bij jouw zakelijke behoeften.

twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

theme_color: '#5C6BC0'

fixed_navbar: top

# Build settings
markdown: kramdown
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Bulma clean theme instellingen
footer_menu: footer_menu

# blog instellingen
paginate: 5
paginate_path: "/blog/page:num"

# Einde bulma clean theme instellingen

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      hero_image: /assets/images/phone2.jpg
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      show_sidebar: true